### PR TITLE
qubes-updates-cache: Signal torified proxy to client

### PR DESCRIPTION
**Pull request by rustybird**
Assuming that qubes-updates-cache has been installed on the gateway,
users would manually enable the qubes-updates-cache Qubes service.

### CODE REVIEW

**Comment by adrelanos** [comment]
`/var/run/qubes-service/qubes-updates-proxy` has no direct use rather than being a status file. I wonder if that file should also be created for qubes squid proxy, if another one should be implemented or be totally removed while we are at it.

**Comment by rustybird** [comment]
The (non-caching) proxy's systemd service uses this file as a startup trigger:

https://github.com/QubesOS/qubes-core-agent-linux/blob/master/vm-systemd/qubes-updates-proxy.service#L4

Conversely, the cache's systemd service uses it to inhibit startup, because otherwise both services would try to bind to port 8082:

https://github.com/rustybird/qubes-updates-cache/blob/master/usr/lib/systemd/system/qubes-updates-cache.service#L4

**Comment by rustybird** [comment]
Wait a sec... What would you think about a simplified commit that also allows a workstation to act as an update proxy or cache?

**Comment by adrelanos** [comment]
Rusty Bird:
> The (non-caching) proxy's systemd service uses this file as a startup trigger:
> 
> https://github.com/QubesOS/qubes-core-agent-linux/blob/master/vm-systemd/qubes-updates-proxy.service#L4
> 
> Conversely, the cache's systemd service uses it to inhibit startup, because otherwise both services would try to bind to port 8082:
> 
> https://github.com/rustybird/qubes-updates-cache/blob/master/usr/lib/systemd/system/qubes-updates-cache.service#L4

Thanks for pointing me at that!

Perhaps these lines should be commented since that mechanism is not obvious?

**Comment by adrelanos** [comment]
Rusty Bird:
> Wait a sec... What would you think about a simplified commit that also allows a workstation to act as an update proxy or cache?

If you can test, that this works, that would be awesome!

**Comment by rustybird** [comment]
>> Wait a sec... What would you think about a simplified commit that also allows a workstation to act as an update proxy or cache?

> If you can test, that this works, that would be awesome!

Turns out it can't work, because there's no PR-QBS-SERVICES chain on workstations. There's also no filtering for forwarded traffic, so -- independent of this pull request -- I think it would be a good idea to totally disable IP forwarding in workstations, where it is currently enabled by /etc/sysctl.d/80-qubes.conf.

Anyway, there's still no harm in allowing users to manually enable the qubes-updates-proxy or -cache service. It doesn't affect the presence or absence of forward filtering, and maybe at some point workstations will have regular Qubes firewalling.

> Perhaps these lines should be commented since that mechanism is not obvious?

Sure, done.

**Comment by rustybird** [comment]
Added another commit on top

**Comment by adrelanos** [comment]
This is an interesting idea. Instead of dynamically patching the html files during boot, these files are patched during the qubes-whonix package build process. This could be more stable than the current implementation.

However, now these modified files will also end up in the workstation and in the TemplateVMs.

* Modified files in workstations: Probably okay, unless someone wanted to use tinyproxy inside the workstation for its own purposes. I guess that would be such a minority use case so we can discard that.
* Modified files in the TemplateVMs: We need to make really sure neither tinyproxy nor squid are ever started in the TemplateVMs.

**Comment by rustybird** [comment]
We can solve both of these problems by using a custom error page location for both qubes-updates-proxy and -cache. Working on it...

**Comment by rustybird** [comment]
Okay, I backed out of the second commit and modified the first commit to use /etc/qubes-updates-cache/errors/ERR_INVALID_URL.

If/when qubes-updates-cache has been packaged and qubes-updates-proxy has been modified to also use a distinct path, I'll submit another PR with the second commit and drop-in files to prevent -proxy and -cache from starting in templates.

**Comment by adrelanos** [comment]
The file location in /etc is problematic. When that file is dynamically modified and later and apt-get dist-upgrade is performed, it could lead to an dpkg interactive conflict resolution dialog, which is to be avoided. Does that file belong into /etc? Should it be considered a user editable config file? Would not /usr/share/... be better?

**Comment by adrelanos** [comment]
Actually, I am very much interested to avoid the dynamic file edit. Because of this Qubes-Whonix bug which is still not fully solved in Whonix 13 apparently...

`Templates incorrectly think they're not connected to a Whonix gateway.`
https://forums.whonix.org/t/templates-incorrectly-think-theyre-not-connected-to-a-whonix-gateway

But this is of course not work I can blame on you, however I'd be glad if you are working on this.

**Comment by rustybird** [comment]
> Would not /usr/share/... be better?

You're right, what was I thinking

> Actually, I am very much interested to avoid the dynamic file edit.

Done in the new commit series. (The third commit can be reversed when qubes-updates-cache is available as a package.)

Changing qubes-updates-proxy to use a distinct error file and the vm-updates user/group is still to be done, but not urgently IMHO.

Another minor thing: If the new qubes-whonix package is built on a VM where the old version of qubes-whonix-sysinit already dynamically modified the tinyproxy error page, then the magic line will appear twice. But as it's just a cosmetic problem that will fix itself automatically with some subsequent build, I didn't add a workaround to the add-magic-proxy-line stdin-to-stdout filter script.

> Modified files in the TemplateVMs: We need to make really sure neither tinyproxy nor squid are ever started in the TemplateVMs.

Come to think of it, why? If they're started in a TemplateVM (because the user has manually enabled the qubes-updates-proxy or -cache service or something), the Qubes firewall will block tinyproxy/squid upstream traffic like all other traffic that's not to 10.137.255.254:8082 in a TemplateVM.

**Comment by adrelanos** [comment]
Rusty Bird:
>> Modified files in the TemplateVMs: We need to make really sure
>> neither tinyproxy nor squid are ever started in the TemplateVMs.
> Come to think of it, why? If they're started in a TemplateVM (because
> the user has manually enabled the qubes-updates-proxy or -cache
> service or something), the Qubes firewall will block tinyproxy/squid
> upstream traffic like all other traffic that's not to
> 10.137.255.254:8082 in a TemplateVM.

Due to files that may be created in the TemplateVM by tinyproxy or squid
if they are running. Which would then be persistent and be inherited in
TempalteBasedVMs where they may be causing issues.

**Comment by rustybird** [comment]
I don't get it... If the user manually starts a service (or any program) in a TemplateVM, then yes, it may create files which are inherited by the TemplateBasedVMs. But isn't that expected behavior, and already the case without these commits? Though maybe there's some extra trickyness about tinyproxy/squid I haven't considered, or something Whonix specific.

**Comment by adrelanos** [comment]
If the user manually starts the service fine. My point was only to make
sure the service does not run by default in the TemplateVM.

**Comment by rustybird** [comment]
Oh I see, that makes sense. They won't start automatically.

**Comment by rustybird** [comment]
To expand on that, -cache never starts automatically at all, and -proxy only starts automatically via this file (condition: VM type == NetVM):

https://github.com/QubesOS/qubes-core-agent-linux/blob/master/vm-systemd/qubes-sysinit.sh#L4

Or this file (condition: VM type != TemplateVM):

https://github.com/rustybird/qubes-whonix/blob/qubes-updates-cache/usr/lib/qubes-whonix/init/qubes-whonix-sysinit#L27-L30

**Comment by adrelanos** [comment]
This looks good so far.

Have you tested this? Both qubes-updates-proxy and qubes-updates-cache would be functional?

The following is something that also I could do if you wish... (I appreciate you doing it a lot! I cannot guess you interest and temper related to this PR.) I am wondering if the transform for tinyproxy error file is required. It could also be made a simple displace.

**Comment by rustybird** [comment]
> Have you tested this? Both qubes-updates-proxy and qubes-updates-cache would be functional?

Yes.

> I cannot guess you interest and temper related to this PR.

*lol* don't worry!

> I am wondering if the transform for tinyproxy error file is required. It could also be made a simple displace.

You mean, ship the premodified tinyproxy error page in the qubes-whonix git repository and package?

**Comment by adrelanos** [comment]
Glad we sorted that out!

>> I am wondering if the transform for tinyproxy error file is required. It could also be made a simple displace.
> 
> You mean, ship the premodified tinyproxy error page in the qubes-whonix git repository and package?

Yes.

**Comment by rustybird** [comment]
Done

**Comment by adrelanos** [comment]
Very good!

-----

A related point since we are at it... What about this mechanism to issue starting tinyproxy in sys-whonix... It blows my mind. Summarized below.

* [`/lib/systemd/system/qubes-whonix-sysinit.service`](https://github.com/Whonix/qubes-whonix/blob/master/lib/systemd/system/qubes-whonix-sysinit.service)
 * [`/usr/lib/qubes-whonix/init/qubes-whonix-sysinit`](https://github.com/rustybird/qubes-whonix/blob/qubes-updates-cache/usr/lib/qubes-whonix/init/qubes-whonix-sysinit)
   *  `touch /var/run/qubes-service/qubes-updates-proxy`
* [`/lib/systemd/system/qubes-updates-proxy.service`](https://github.com/QubesOS/qubes-core-agent-linux/blob/master/vm-systemd/qubes-updates-proxy.service)
 * `ConditionPathExists=|/var/run/qubes-service/qubes-updates-proxy`
* [`/lib/systemd/system/qubes-updates-proxy.service.d/40_qubes-whonix.conf`](https://github.com/Whonix/qubes-whonix/blob/master/lib/systemd/system/qubes-updates-proxy.service.d/40_qubes-whonix.conf)

`qubes-whonix-sysinit.service` could easily have messed up dependencies, i.e. run after `qubes-updates-proxy.service`, thereby tinyproxy not starting. Currently `qubes-whonix-sysinit.service` dependencies might even be wrong. A likely source of race conditions perhaps?

 I am wondering what you think about this mechanism?

1) Perhaps `/usr/lib/qubes-whonix/init/qubes-whonix-sysinit` could be abolished? Replaced with a systemd unit file?
2) Likely the status file `/var/run/qubes-service/qubes-updates-proxy` creation should be moved to its own systemd unit file? Or into `/lib/systemd/system/qubes-updates-proxy.service.d/40_qubes-whonix.conf`?

**Comment by rustybird** [comment]
> qubes-whonix-sysinit.service could easily have messed up dependencies, i.e. run after qubes-updates-proxy.service, thereby tinyproxy not starting.

I don't think so, because the name qubes-whonix-sysinit.service (correctly) hints at it being part of sysinit.target, and qubes-updates-proxy.service doesn't specify DefaultDependencies=false.

    systemctl list-dependencies --reverse          qubes-whonix-sysinit.service
    systemctl list-dependencies --reverse --before qubes-whonix-sysinit.service

> 1) Perhaps /usr/lib/qubes-whonix/init/qubes-whonix-sysinit could be abolished? Replaced with a systemd unit file?
> 2) Likely the status file /var/run/qubes-service/qubes-updates-proxy creation should be moved to its own systemd unit file? Or into /lib/systemd/system/qubes-updates-proxy.service.d/40_qubes-whonix.conf?

Something like that, e.g. qubes-whonix-sysinit.service's ExecStart and ExecStartPre seem unrelated to each other, and maybe some of the legacy code in ExecStartPre can be removed.

**Comment by rustybird** [comment]
Yay, thanks!

**Comment by adrelanos** [comment]
I added the above discussed refactoring. I would appreciate if you could have a look!

https://github.com/adrelanos/qubes-whonix/commit/4d9e38304050c4fd1ea49b08078298da10939d5c

**Comment by rustybird** [comment]
Added some nitpicks as line notes. Otherwise, looks good to me.

**Comment by adrelanos** [comment]
All suggestions added!

https://github.com/Whonix/qubes-whonix/commit/064bc2b32d7f985d37501d884722a2f79a715500

**Comment by adrelanos** [comment]
I guess the following now could/should be removed?

```
## Only enable qubes-updates-proxy in sys-whonix.
ConditionPathExists=/usr/share/anon-gw-base-files/gateway
```

**Comment by rustybird** [comment]
Hmm yes, looks like the line just prevents -proxy from being enabled on NetVM/ProxyVM *workstations* (once the legacy stuff is gone). I can see no harm in removing it.

**Comment by adrelanos** [comment]
Done.

**Pull request merged**
